### ISSUE TITLE
Using cogs function with nested data frame

### ISSUE THREAD

**Issue by mwhitaker** [hafen/trelliscopejs#15]
Thank you for a wonderful package! I am trying to use your [example](https://hafen.github.io/trelliscopejs/rd.html#panels) and add a `cog` column, but it's ignored in the final output:

    ggplot2::mpg %>%
      group_by(manufacturer, class) %>%
      nest() %>%
      mutate(mean_city_mpg=cogs(data, ~ cog(mean(.x$cty), desc = "Mean city mpg"))) %>%
      mutate(panel = panels(data, ~ figure(xlab = "City mpg", ylab = "Highway mpg") %>%
          ly_points(cty, hwy, data = .x))) %>%
      trelliscope(name = "city_vs_highway_mpg", nrow = 1, ncol = 2)

Could you let me know how to apply cognostics to nested data frames?

Kind regards,
Michael

**Comment by hafen** [comment]
Thanks! Here's a few tweaks to your code so that your additional cognostics show up:

```r
ggplot2::mpg %>%
  group_by(manufacturer, class) %>%
  nest() %>%
  mutate(
    additional_cogs = cogs(data,
      ~ data_frame(mean_city_mpg = cog(mean(.x$cty), desc = "Mean city mpg"))),
    panel = panels(data, ~ figure(xlab = "City mpg", ylab = "Highway mpg") %>%
      ly_points(cty, hwy, data = .x))) %>%
  trelliscope(name = "city_vs_highway_mpg", nrow = 1, ncol = 2)
```

(note that you could separate the `mutate()` into two different calls as in the code you supplied if you'd like)

The key here is that for `trelliscope()` to pick up cognostics, they either need to be atomic columns of the data frame, or a list-column containing data frames. If a list-column data frame has multiple rows (such as the `data` column you get after calling `nest()`), it will try to compute some "automatic cognostics" for each of these. You can disable this with `auto_cog = FALSE`. If it finds any list-columns of single-row data frames, it will just use whatever is in that data frame as-is as cognostics. So in your example, all that was missing was casting the result of your mutate as a data frame. Note that you can name the result of your mutate call to `cogs()` to be whatever you want - what matters is what you name the columns of the resulting data frame.

I apologize this particular case isn't particularly well-documented right now. I haven't put this on CRAN yet because I want to make sure the tidy pipeline is as intuitive as possible. If you have suggestions or thoughts about ways you would expect it to work, let me know.

**Comment by mwhitaker** [comment]
Thanks @hafen that works. The only thing not showing up for me is `desc = "Mean city mpg"` in the Labels. One suggestion would be to add this example to [cogs](https://github.com/hafen/trelliscopejs/blob/master/R/helpers.R#L58)  just like you did for [panels](https://github.com/hafen/trelliscopejs/blob/master/R/helpers.R#L32).

I have been changing my workflow to use [list-columns](http://r4ds.had.co.nz/many-models.html#creating-list-columns) and it's great to see you using that approach. Models and now plot objects all in one neat structure!

**Comment by hafen** [comment]
I added an example and made it so that nested cog attributes are preserved (so your description should be honored now).

Yes, I agree, the plots as list-columns makes a lot of sense!

**Comment by mwhitaker** [comment]
Thanks Ryan. Works great on my end!
